language: java
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq debhelper
- sudo apt-get install -qq dh-virtualenv
script:
- mvn clean install
- cd delivery/delivery/
- bash debbuild.sh

dist: trusty